# Generated by Django 5.1.5 on 2025-01-19 21:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_task_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='DE', unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='join_app.contact'),
        ),
    ]
