# Generated by Django 5.1.5 on 2025-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_alter_contact_phone_alter_task_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='prio',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'urgent'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=20),
        ),
    ]
