# Generated by Django 5.1.5 on 2025-01-20 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_remove_task_prio_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('awaitfeedback', 'Awaiting Feedback'), ('done', 'Done')], max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assignedTo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='dueDate',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='join_app.taskcategory'),
        ),
    ]
