# Generated by Django 5.1.5 on 2025-01-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_remove_task_subtasks_task_currentprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
