# Generated by Django 5.1.5 on 2025-01-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_alter_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
