# Generated by Django 5.1.5 on 2025-01-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0014_alter_contact_phone_alter_task_assignedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
